#!/usr/bin/env python3
"""Validate that .vercelignore keeps the Vercel source upload scoped to Flutter Web.

Vercel does NOT honour .gitignore when it collects deployment files, so every
local build artefact is uploaded unless .vercelignore excludes it. Before this
guard existed the source upload was 11,831 files / 2,122 MB, dominated by
build/, backend/ and .dart_tool/.

This runs in CI without Vercel credentials, so it cannot perform a live dry run.
Instead it applies .vercelignore's own matching rules to a fixed set of probe
paths and asserts both halves of the contract:

  * heavy / irrelevant / secret-bearing paths ARE excluded, and
  * everything `flutter build web` needs is NOT excluded.

Exit status 0 = contract holds, 1 = violated.
"""

from __future__ import annotations

import sys
from fnmatch import fnmatch
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
VERCELIGNORE = REPO_ROOT / ".vercelignore"

# Paths that must be excluded from the upload, with the reason shown on failure.
MUST_EXCLUDE: list[tuple[str, str]] = [
    ("backend/Dockerfile", "the .NET backend deploys to Render, not Vercel"),
    ("backend/src/CaloriesTracking.Api/Program.cs", "backend source"),
    ("backend/src/CaloriesTracking.Api/calories.db", "local database file"),
    ("build/web/main.dart.js", "build output is regenerated on Vercel"),
    ("build/app/outputs/flutter-apk/app-release.apk", "Android build artefact"),
    (".dart_tool/package_config.json", "tool cache is regenerated by pub get"),
    (".flutter-sdk/bin/flutter", "SDK is installed by the build script"),
    ("coverage/lcov.info", "coverage report"),
    ("android/build.gradle", "non-web platform source"),
    ("ios/Runner/Info.plist", "non-web platform source"),
    ("linux/CMakeLists.txt", "non-web platform source"),
    ("macos/Runner/Info.plist", "non-web platform source"),
    ("windows/CMakeLists.txt", "non-web platform source"),
    ("test/widget_test.dart", "tests run in CI, not in the Vercel build"),
    ("integration_test/app_test.dart", "tests run in CI, not in the Vercel build"),
    ("docs/DEPLOYMENT_GUIDE.md", "documentation"),
    (".github/workflows/flutter-ci.yml", "CI configuration"),
    ("scripts/ci/check.sh", "CI-only tooling"),
    ("scripts/process_usda.py", "dataset tooling, not used by the web build"),
    (".env", "local environment file must never enter the source upload"),
    (".env.local", "local environment file must never enter the source upload"),
    ("data/foods.db", "local database file"),
    ("data/foods.sqlite", "local database file"),
    ("data/foods.sqlite3", "local database file"),
]

# Paths the Flutter Web build genuinely needs; excluding any of them breaks it.
MUST_INCLUDE: list[str] = [
    "lib/main.dart",
    "web/index.html",
    "web/manifest.json",
    "assets/images/logo.png",
    "pubspec.yaml",
    "pubspec.lock",
    "analysis_options.yaml",
    ".metadata",
    "vercel.json",
    "scripts/vercel-build.sh",
]


def load_patterns(path: Path) -> list[str]:
    """Return the non-comment, non-blank patterns from a .vercelignore file."""
    patterns: list[str] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        patterns.append(line)
    return patterns


def is_ignored(candidate: str, patterns: list[str]) -> bool:
    """Approximate Vercel's .gitignore-style matching for a repo-relative path.

    A pattern matches when it equals a path segment prefix (directory rules such
    as `backend/`), when it equals the full path, or when it globs the full path
    or any single segment (rules such as `*.db`).
    """
    parts = candidate.split("/")
    for pattern in patterns:
        # Negation rules would re-include a path; treat them as non-matching so a
        # stray `!` can never make this check pass by accident.
        if pattern.startswith("!"):
            continue

        normalised = pattern.rstrip("/")

        # Directory prefix: `backend/` ignores everything beneath backend/.
        if candidate == normalised or candidate.startswith(normalised + "/"):
            return True

        # Glob against the whole path, e.g. `scripts/ci/*`.
        if fnmatch(candidate, normalised):
            return True

        # Glob against any single segment, e.g. `*.db` or `.env.*`.
        if any(fnmatch(part, normalised) for part in parts):
            return True

    return False


def main() -> int:
    if not VERCELIGNORE.is_file():
        print("FAIL: .vercelignore is missing from the repository root.")
        print("      Without it Vercel uploads build/, backend/ and .dart_tool/")
        print("      on every deployment (previously 2,122 MB).")
        return 1

    patterns = load_patterns(VERCELIGNORE)
    if not patterns:
        print("FAIL: .vercelignore contains no active patterns.")
        return 1

    failures: list[str] = []

    for path, reason in MUST_EXCLUDE:
        if not is_ignored(path, patterns):
            failures.append(f"  - {path} is NOT excluded ({reason})")

    for path in MUST_INCLUDE:
        if is_ignored(path, patterns):
            failures.append(f"  - {path} IS excluded but the web build needs it")

    if failures:
        print("FAIL: .vercelignore does not scope the upload correctly.")
        print("\n".join(failures))
        return 1

    print(
        f"OK: .vercelignore active patterns={len(patterns)}; "
        f"{len(MUST_EXCLUDE)} heavy/secret paths excluded, "
        f"{len(MUST_INCLUDE)} Flutter Web inputs preserved."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
